--- #YAML:1.0
name:               PJob
version:            0.17
abstract:           POE Job Server
author:
    - woosley.xu
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Any::Moose:       0
    List::MoreUtils:  0
    List::Util:       0
    POE:              0
    POSIX:            0
    Scalar::Util:     0
    Term::ANSIColor:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
