---
abstract: 'POE Job Server/Client'
author:
  - woosley.xu
generated_by: 'Dist::Zilla version 1.093000'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PJob
requires:
  Any::Moose: 0
  List::MoreUtils: 0
  List::Util: 0
  POE::Component::Client::TCP: 0
  POE::Component::Server::TCP: 0
  POE::Wheel::Run: 0
  POSIX: 0
  Scalar::Util: 0
  Term::ANSIColor: 0
resources:
  repository: http://github.com/woosley/Perl-PJob
version: 0.19
